version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'db-data:/var/lib/mysql'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - .:/rails-dev
    ports:
      - "3002:3002"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - DATABASE_USER=root
      - RAILS_MAX_THREAD=5
      - DATABASE_PASSWORD=password

volumes:
  db-data: